# Generated by Django 5.0.6 on 2024-05-26 17:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogtagmodel',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='test_editor',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True),
        ),
    ]
