# Generated by Django 5.0.6 on 2024-05-26 17:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogtagmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='test_editor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
