# Generated by Django 5.0.6 on 2024-05-26 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogmodel_test_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='blog-photos'),
        ),
    ]
