# Generated by Django 5.0.6 on 2024-05-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategorymodel_head_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='head_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.productcategorymodel'),
        ),
    ]
